"""Repository abstraction (spec #31).

Application/business layers depend ONLY on `Repository`. SQLite and in-memory
implementations are interchangeable; neither leaks SQL semantics upward.
"""

from __future__ import annotations

from typing import Protocol

from ..domain.models import (
    Competitor,
    Entity,
    Evidence,
    IntelligenceReport,
    Opportunity,
    ResearchJob,
    Signal,
    Snapshot,
)


class Repository(Protocol):
    # research jobs
    def save_job(self, job: ResearchJob) -> None: ...
    def get_job(self, research_id: str) -> ResearchJob | None: ...
    def find_job_by_idempotency_key(self, key: str) -> ResearchJob | None: ...

    # entities
    def upsert_entity(self, entity: Entity) -> None: ...
    def get_entity(self, entity_id: str) -> Entity | None: ...
    def save_competitors(self, prospect_entity_id: str, research_id: str, competitors: list[Competitor]) -> None: ...

    # evidence (idempotent upsert by evidence_id)
    def upsert_evidence(self, evidence: list[Evidence]) -> int: ...
    def get_evidence(self, evidence_ids: list[str]) -> list[Evidence]: ...
    def count_evidence(self) -> int: ...

    # snapshots (append-only, immutable)
    def save_snapshot(self, snapshot: Snapshot) -> None: ...
    def get_snapshot(self, snapshot_id: str) -> Snapshot | None: ...
    def latest_snapshot_before(self, prospect_entity_key: str, captured_at: str) -> Snapshot | None: ...
    def list_snapshots(self, prospect_entity_key: str) -> list[Snapshot]: ...

    # derived
    def save_signals(self, research_id: str, signals: list[Signal]) -> None: ...
    def save_opportunities(self, research_id: str, opportunities: list[Opportunity]) -> None: ...

    # reports
    def save_report(self, report: IntelligenceReport) -> None: ...
    def get_report(self, research_id: str) -> IntelligenceReport | None: ...
    def latest_report(self, prospect_entity_key: str, before: str | None = None) -> IntelligenceReport | None: ...
    def list_reports(self, prospect_entity_key: str) -> list[IntelligenceReport]: ...

    def close(self) -> None: ...
